development:
  base_url: http://localhost:3000
  payment_url: http://localhost:5000
production:
  base_url: https://example.com.br
test:
  base_url: http://0.0.0.0:4000
  payment_url: http://payment.com.br
