default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %> 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db

development:
  <<: *default
  database: esperto_fit_academy_development

test:
  <<: *default
  database: esperto_fit_academy_test

production:
  <<: *default
  database: esperto_fit_academy_production
